theme: jekyll-theme-cayman
title: GitHub Pages with Jekyll
description: A Full Guide for GitHub Pages with the famous SSG (Static Site Generator), Jekyll
author: Vatsal Saxena
baseurl: "/repository-name"
